# language:
#   Changes plugin's locale. (generally affects all end-user seen messages)
#   Out-of-the-box translations:
#   en — ENGLISH
#   ru — RUSSIAN (Русский)
#
#     It is also possible to change the language to whatever language you need as long
#   as you create an alternative locale-{language}.yml file with the translation inside.
language: en

# storage-method:
#   Changes the method of storing your whitelist.
#   Supported methods:
#   json — Simple JSON-based whitelist file. All whitelistable players are
#       once loaded and then cached. Saves on each update.
#   database — connects to database with database.yml configuration.
storage-method: json

whitelist:
  enabled: false
  # uuid-mode:
  #   Changes the algorithm of fetching user's UUID in a several commands.
  #   If you need to add, remove etc. a specific UUID you'll find a special
  #     version of each command for this purpose.
  #   Supported modes:
  #   auto — RECOMMENDED checks whether the server is in online or offline mode
  #       and automatically chooses between online and offline uuid-mode's
  #   online — requests Mojang for player's UUID
  #       (server.properties online-mode: true behaviour)
  #   offline — calculates offline UUID
  #       (server.properties online-mode: false behaviour)
  #
  # WARNING: the plugin DOES NOT convert your offline UUIDs to online and vice-versa.
  #           You should either stick to one or another, or alternatively .
  uuid-mode: auto

#   When both whitelist and auto-whitelist are enabled, the plugin will automatically
# add a joining player of selected group to the whitelist for the specified duration.
#
#   A single player can only get automatically whitelisted "max-repeats" times.
# So if it's set to 2, after the first period they will be able to get extra time.
# * It won't work the second time IF they do not meet current strategy requirements.
#
#   Strategies select a group of players who will be automatically whitelisted
# upon joining the server.
auto-whitelist:
  enabled: true
  #   Any value in range (-∞;0] will be treated as permanent whitelisting,
  # WHICH SHOULD NOT BE USED (because then what's the point in using a whitelist?)
  #
  #   Any value that can not be parsed will result in disabling the automatic
  # whitelisting feature until the configuration is fixed and reloaded.
  duration: 7d
  #  Any value in range (-∞;0] will disable the auto whitelisting.
  # Although, it should not be used that way, because if you want to disable this feature
  # then simply disable it, using < 1 "max-repeats" will still make the plugin run multiple
  # checks when a player logins, wastefully spending your important clock-cycles and their
  # login time.
  max-repeats: 1
  # all — simply every joining player if the number that they've been "freely" whitelisted
  #       have yet to exceed the limiting "max-repeats" property.
  #
  # newcomers — only those players who have never player on this server before.
  #       This strategy makes use of Bukkit's #hasPlayerBefore() method that checks
  #       whether the server has any data on the given player. This will always
  #       be true if you disable the property «players.disable-saving» in spigot.yml
  strategy: newcomers
