name: VoidWhitelist
version: ${project.version}b${buildNumber}-${version.stability}
main: voidpointer.spigot.voidwhitelist.VoidWhitelistPlugin
api-version: 1.13
authors: [ _voidpointer ]
description: Mixed UUID based whitelist with the possibility of temporary addition.
website: github.com/voidpointer0x00/VoidWhitelist
softdepend: [ floodgate, PlaceholderAPI ]

commands:
  whitelist:
    description: Main command which includes all the rest - add, remove etc.
    permission: 'voidwhitelist.whitelist' # this is new

permissions:
  voidwhitelist.whitelist:
    description: 'Allows to use the /whitelist command'
  voidwhitelist.whitelist.add:
    description: 'Allows to add players to whitelist'
  voidwhitelist.whitelist.remove:
    description: 'Allows to remove players from whitelist'
  voidwhitelist.whitelist.off:
    description: 'Allows to turn-off the whitelist'
  voidwhitelist.whitelist.help:
    description: 'Allows to get list of whitelist commands and their description'
  voidwhitelist.whitelist.reload:
    description: 'Allows to reload configuration'
  voidwhitelist.whitelist.reconnect:
    description: 'Allows to forcefully reconnect to database'
  voidwhitelist.whitelist.gui:
    description: 'Allows to use GUI'
  voidwhitelist.whitelist.import-json:
    description: 'Allows to import whitelist from JSON format to database'
  voidwhitelist.whitelist.export-db:
    description: 'Allows to export database into JSON format files'
  voidwhitelist.whitelist.on:
    description: 'Allows to turn-on the whitelist'
  voidwhitelist.whitelist.info:
    description: 'Allows to get whitelist information of a player'
  voidwhitelist.whitelist.status:
    description: 'Allows to check whether the whitelist is on or off'

  voidwhitelist.whitelist.*:
    description: 'Wildcard permission for all /whitelist children'
    children:
      voidwhitelist.whitelist.add: true
      voidwhitelist.whitelist.remove: true
      voidwhitelist.whitelist.off: true
      voidwhitelist.whitelist.help: true
      voidwhitelist.whitelist.reload: true
      voidwhitelist.whitelist.reconnect: true
      voidwhitelist.whitelist.gui: true
      voidwhitelist.whitelist.import-json: true
      voidwhitelist.whitelist.export-db: true
      voidwhitelist.whitelist.on: true
      voidwhitelist.whitelist.info: true
      voidwhitelist.whitelist.status: true


