name: VoidWhitelist
version: ${project.version}b${buildNumber}-${version.stability}
main: voidpointer.spigot.voidwhitelist.VoidWhitelistPlugin
api-version: 1.18
authors: [ _voidpointer ]
description: Mixed UUID based whitelist with the possibility of temporary addition.
website: github.com/voidpointer0x00/VoidWhitelist

commands:
  whitelist:
    description: Main command which includes all the rest - add, remove etc.
