name: VoidWhitelist
version: ${project.version}
main: voidpointer.spigot.voidwhitelist.VoidWhitelistPlugin
api-version: 1.17
authors: [ _voidpointer ]
description: Mixedd UUID based whitelist with the possibility of temporary addition.
website: vk.me/voidpointer

commands:
  whitelist:
    description: Main command which includes all the rest - add, remove etc.
